add_newline = false
# command_timeout = 3000
format = """
$time$directory$golang$nodejs$python$dart$rust$deno$ruby$cmd_duration$fill$git_status$git_branch
$character"""

[character]
success_symbol = "ğŸ¦„ " 
error_symbol = "ğŸ¥º "

[git_status]
style = "bold white"
conflicted = " ğŸ³"
ahead = " ğŸğŸ’¨ "
behind =" ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤·â€ "
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](green)'
renamed = " ğŸ‘… "
deleted = " ğŸ—‘ "

[gcloud]
disabled = true

[aws]
disabled = true

# languages
[golang]
format = "[$symbol($version )]($style)"
symbol = "î˜§ "

[nodejs]
format = "[$symbol($version )]($style)"

[python]
format = "[$symbol($version )]($style)"

[dart]
format = "[$symbol($version )]($style)"

[rust]
format = "[$symbol($version )]($style)"

[deno]
format = "[$symbol($version )]($style)"

[ruby]
format = "[$symbol($version )]($style)"

